### ISSUE TITLE
This is not a real issue, just a thanks

### ISSUE THREAD

**Issue by xuantiep** [Sorok-Dva/freenom-auto-renew-domains#10]
hey,
i just want to say thank you, your git is so great for me cause i have lot of domain there at freenom, and i need this, cause my head memory is nearly full because of life stuff, and the internet... that terrible.
Now i can sleep well with your git auto renewal, thankyou so much, i love youuuu

**Comment by Sorok-Dva** [comment]
Thanks @xuantiep ! I appreciate your message ! Enjoy this tool :)
