### ISSUE TITLE
i will going to sponsor for the project

### ISSUE THREAD

**Issue by xuantiep** [Sorok-Dva/freenom-auto-renew-domains#16]
Hi,

i'm very pleasure for your hard work gained to the community all around the world, just because this is end of the month so i'm not having much to sponsor the project, but promise to sponsor more in the next month as i can.

thanks much, and love from here.

**Comment by xuantiep** [comment]
also if you need private server please do not hesistate to pm me, i will grant free no cost server if you want.

**Comment by Sorok-Dva** [comment]
Thank you very much @xuantiep for you support ! I appreciate that and it motivates me to continue this project :) I'm glad that you love it !

**Comment by xuantiep** [comment]
yeah i love it very much as you can see, that i check the reposity almost everyday. thanks again for your hard work. love you much.
