### ISSUE TITLE
Sending webhook notification exceeds 2000 character limit

### ISSUE THREAD

**Issue by Bartkk0** [Sorok-Dva/freenom-auto-renew-domains#2]
![image](https://user-images.githubusercontent.com/32180149/147728502-5951d9f1-655a-44a9-a1f0-795acf448d5c.png)

**Comment by Sorok-Dva** [comment]
Hello, please could you send a screenshot of your domains list (keep them secret) on freenom ? Maybe you have to much domains so that's why you have this error, and I'll need to divide the message if it's the case.

**Comment by Bartkk0** [comment]
I have 28 domains on freenom in total, so it's probably too much.

**Comment by Sorok-Dva** [comment]
Ok yes this is probably where is the problem. I'll push a fix this week (probably this week-end)

**Comment by Sorok-Dva** [comment]
Hello @Bartkk0, please could you test on this branch https://github.com/Sorok-Dva/freenom-auto-renew-domains/tree/fix/webhookContentSize if you now have still the problem please.

I did some tries with some lorem ipsum texts and it's working, all domains are sent one per one, but I don't know if it's working as expected without the lorem ipsum

![image](https://user-images.githubusercontent.com/15158794/149324823-66705949-a7c5-41af-8c78-deba389a1c30.png)
> Each blocks is a single discord message

**Comment by Bartkk0** [comment]
Sorry for not replying, tried the branch and it appears that length error was fixed, but now it sends 5 messages and then it's rate limited.
![image](https://user-images.githubusercontent.com/32180149/154876407-56f4b0e6-db52-4e52-a986-ac7e9b0a468d.png)

**Comment by Bartkk0** [comment]
Fixed it somewhat in #4
