### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by abramovantonru** [Sorok-Dva/freenom-auto-renew-domains#21]
Start tool with docker-compose by 
`docker-compose up -d `

and get error ->
![image](https://user-images.githubusercontent.com/20409030/200624733-c1419e37-31d6-4d99-a333-15a61b58da38.png)

if remove from docker-compose.yml property
`build.target = dev`
get error -> 
![image](https://user-images.githubusercontent.com/20409030/200626045-bb92268c-7ea2-4ada-8152-56f97e17474e.png)

**Comment by Sorok-Dva** [comment]
Hi.

Did you try using `make` command ? 
You should use : 

```shell
make .env
make
make start
```

![image](https://user-images.githubusercontent.com/15158794/200866169-fd7a1884-212e-4b6f-9dbf-302540b0dc30.png)

**Comment by abramovantonru** [comment]
Sorry, i'm not use `make`.

I try use and get this ->

![image](https://user-images.githubusercontent.com/20409030/200906933-67152d51-9b8c-4dd5-9387-e6d72c470728.png)

in `.env` var `DISCORD_TOKEN` is set

**Comment by Sorok-Dva** [comment]
Ok my bad there was a mistake in the .env file.

The env var is `DISCORD_BOT_TOKEN` instead of `BOT_TOKEN` or `DISCORD_TOKEN`

**Comment by abramovantonru** [comment]
okay, works
