### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Dipuuu111** [Sorok-Dva/freenom-auto-renew-domains#6]
Well i wanted to run this app but gave me an issue on www.replit.com as it can run 24/7.
it say it can't find .env even though it is stored in secrets and could you plz tell how to use webhooks as it give only url and it requires token no.
thankyou

**Comment by Dipuuu111** [comment]
you can find it here : https://replit.com/@Diptanshu11/freenom-auto-renew-domains#.replit

**Comment by Sorok-Dva** [comment]
Hello,

I don't know replit, try to reach their support to know how to define your .env variables.

About the webhook, all the data is in the url, it's just splitted,

Exemple : https://discord.com/api/webhooks/**953769142413041664**/**RAE2yQ3uY-HoRRT6HDrLh-m_Fg7-i-FyCzgjGN5tB14N5nMSMB7GqVAYUyL0L78JkSC-**

DISCORD_WEBHOOK_ID=953769142413041664
DISCORD_WEBHOOK_TOKEN=RAE2yQ3uY-HoRRT6HDrLh-m_Fg7-i-FyCzgjGN5tB14N5nMSMB7GqVAYUyL0L78JkSC-

**Comment by Dipuuu111** [comment]
ok thanks
